### ISSUE TITLE
合入配置后，需要按两次Esc键才能从insert模式退回到normal模式

### ISSUE THREAD

**Issue by t6ui** [skywind3000/vim-init#1]
我把init-config.vim这个文件合入到我的vim配置中，出现标题中描述的现象。第一次按下Esc的时候如果时间等待稍长一些（1S）才能恢复正常模式，如果快速按下Esc和其他字母按键，会出现一些奇怪的字符。我已经设置ttimeoutlen值为50了。

排查原因是【终端下允许 ALT，详见：http://www.skywind.me/blog/archives/2021】这段配置引起的，注释掉就好了。

另外请教一个问题，wiki中介绍有一句话不明白：
【前面在终端软件里配置好 ALT键，但是 Vim 的话，由于历史原因，需要在你的 vimrc 里加一段键盘码配置】
这里的历史原因是什么，为什么需要另外配置。
还有config.vim中【功能键终端码矫正】是为什么，我以前没有矫正也可以映射相关按键。

我的vim使用环境是：
1.putty连接本地ubuntu虚拟机。
2.ubuntu系统

**Comment by skywind3000** [comment]
尼设置了 `:set ttimeout` 了没有？

**Comment by t6ui** [comment]
已经设置过了。
我单纯使用vim-init是没问题的，可能是我的插件哪里有冲突。
我自己再排查下。
谢谢。
