### ISSUE TITLE
用vim打开某些文件性能降低严重

### ISSUE THREAD

**Issue by if2012** [skywind3000/vim-init#11]
比如下面两个：
https://github.com/vim/vim/blob/master/runtime/autoload/netrw.vim
https://github.com/vim/vim/blob/master/runtime/autoload/pythoncomplete.vim
当G到文件末尾，再滚动光标卡得几乎不能控制。
应该不是文件长度的问题，打开一个几十万行的Makefile文件的时候没有这种现象。

**Comment by skywind3000** [comment]
`.vimrc` 里面加一行：

```VimL
:set re=1
```

再试试。

**Comment by if2012** [comment]
感觉没区别

**Comment by skywind3000** [comment]
那你 

syntime start

然后操作一段时间

syntime report 

看一下正常不。

还有profile一下其他功能排查

**Comment by if2012** [comment]
@skywind3000 这个怎么理解，vim里面命令行输入吗，但是syntime start提示无效的参数。我的vim版本8.1

**Comment by skywind3000** [comment]
记错了，是syntime on

**Comment by if2012** [comment]
把方向键分别映射成hjkl，貌似好多了，我也 不知道啥原因。权宜之计吧，看大神有没有更好的解决方法。

**Comment by skywind3000** [comment]
你用的是 vim-init 配置么？

**Comment by if2012** [comment]
我用的是基于vim-init的[https://github.com/if2012/FlyVim](url)，但我用你原生的测了也是同样的问题。

**Comment by hardboydu** [comment]
在使用 ale 插件的时候，如果编译参数设置不正确导致错误警告太多的话，也会非常慢，例如，打开Linux驱动的代码
