### ISSUE TITLE
leader 键位设置

### ISSUE THREAD

**Issue by fanxiao92** [skywind3000/vim-init#17]
把 Leader 定义成空格，同是 绑定 imap <leader>  组合按键时，vim 需要等待到 timeoutlen  才明白输入的是一个 normal 的空格键位， 在这种情况下导致输入后没有即使反馈，感觉影响到了写入速度，请问有什么方式能够解决这个问题？

**Comment by skywind3000** [comment]
INSERT 模式下，不要定义任何常用字母/数字/空格的 map。INSERT 下面换个键定义下就行了嘛，比如：

```VimL
inoremap <c-b>xx  ....
inoremap <c-b>yy ....
```

**Comment by fanxiao92** [comment]
嗯 Get
