### ISSUE TITLE
无法通过定义 g:bundle_group 关闭 textobj

### ISSUE THREAD

**Issue by yolo2h** [skywind3000/vim-init#18]
https://github.com/skywind3000/vim-init/blob/77a1590af8cf15f1b518de46c4421eb7221f3451/init/init-plugins.vim#L230

最后应该加上 >= 0 吧，因为改了插件，没法提交pull request 了。

**Comment by skywind3000** [comment]
对的。>=0

**Comment by yolo2h** [comment]
ckelsel已修复：https://github.com/skywind3000/vim-init/pull/24
