### ISSUE TITLE
plugin文件夹存在的理由是？

### ISSUE THREAD

**Issue by tracyone** [skywind3000/vim-init#2]
为什么要把外部的插件加到本仓库？

**Comment by skywind3000** [comment]
很正常吧，我看过不少配置都这么干，比如依云的。就和很多项目集成一些必备的配色文件一样。

简单，更新慢，依赖大的插件，集成一下，希望在没有网络的机器上，把 200KB 的配置的压缩包解压一下也能保证最小功能可用，这些插件我也会定期更新。

**Comment by tracyone** [comment]
好吧，我不喜欢这样干。
