### ISSUE TITLE
init-style 拼写错误提示是否不兼容neovim？

### ISSUE THREAD

**Issue by xingezhang** [skywind3000/vim-init#21]
我在neovim下使用，拼写错误提示，无法显示下划线，但是vim没问题，这是neovim的问题吗？

**Comment by skywind3000** [comment]
什么错误提示？？

**Comment by xingezhang** [comment]
init-style重新设定了拼写错误提示，用下划线替代色块那个部分

**Comment by xingezhang** [comment]
我贴一张图就清楚了，左边的是neovim，右边的是vim。
![屏幕快照 2019-05-08 10 53 50](https://user-images.githubusercontent.com/13484700/57385086-c451ef00-717f-11e9-86a4-533b4dd1761b.png)

**Comment by skywind3000** [comment]
你自己调整下呗。

**Comment by skywind3000** [comment]
可能是 neovim 的下划线支持不好？？

**Comment by xingezhang** [comment]
好的，明白了，谢谢！

**Comment by xingezhang** [comment]
仔细排查后，发现问题在set termguicolors；判断一下，如果是gui才设置这个，完美解决。
