### ISSUE TITLE
windows10  下从msys2启动neovim + vim-init，在PlugInstall阶段报错

### ISSUE THREAD

**Issue by structure-charger** [skywind3000/vim-init#31]
新手向大佬求教，neovim+ vim-plug初次在msys2上启动报错：
NO SUCH FILE OR DIRECTORY: C:\\msys2\\usr\\bin\\cmd
有办法hack plugin.vim去支持msys2下启动吗？

**Comment by skywind3000** [comment]
你用的 neovim 是 windows native 版本的，不是 msys2 版本的

**Comment by skywind3000** [comment]
不要混用，从路径上就看得到。
