### ISSUE TITLE
直接换到neovim

### ISSUE THREAD

**Issue by SongTianxian9** [skywind3000/vim-init#35]
各位在云里雾里试着看懂这份配置的vim新手，建议直接切换到neovim，这里的大部分配置都是默认的不需要去设置。请跟上趋势，享受更现代化的vim好吗。readme里批评<leader>建映射的我真是醉了。。。

**Comment by skywind3000** [comment]
不要嘎吹什么 neovim 了，neovim 不让你设置键盘码，这才是最大的问题。terminfo 只有配置不一，你连个纠正的余地都没有，vim 让你设置键盘码，你可以 map 任意键，neovim 却做不到，比如你在 neovim 里 map 一下 `CTRL+0` 我看看？是数字 `0` ，不是字母 `O`。

年轻人，不要动不动就无脑嘎吹，neovim 现在连一个能打的 gui 都没有，还成天秒天秒地的。
一堆比你牛很多的插件作者都还在用着 vim 呢，你瞎激动啥呢。


关于 neovim 的 lua，我早就评论过：

- https://www.zhihu.com/question/445290918/answer/2351039201 


批评两句键位隐射你有啥好醉的，被我说中了么？
这就叫做：上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。

**Comment by SongTianxian9** [comment]
> 不要嘎吹什么 neovim 了，neovim 不让你设置键盘码，这才是最大的问题。terminfo 只有配置不一，你连个纠正的余地都没有，vim 让你设置键盘码，你可以 map 任意键，neovim 却做不到，比如你在 neovim 里 map 一下 `CTRL+0` 我看看？是数字 `0` ，不是字母 `O`。
> 
> 年轻人，不要动不动就无脑嘎吹，neovim 现在连一个能打的 gui 都没有，还成天秒天秒地的。 一堆比你牛很多的插件作者都还在用着 vim 呢，你瞎激动啥呢。
> 
> 关于 neovim 的 lua，我早就评论过：
> 
>     * https://www.zhihu.com/question/445290918/answer/2351039201
> 
> 
> 批评两句键位隐射你有啥好醉的，被我说中了么？ 这就叫做：上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。

键盘码是啥？我为啥要改键盘码？

vim就试过macvim，好不好用不知道，我也从来不用啊，就像emacs，我还是喜欢在终端emacs --no-window啊。

人家vim比我懂的多，遇到问题自己解决了，我不懂啊，我整个简单好用的不行？我觉得neovim用起来更适合我不行，我还管哪个插件作者还在用？

neovim的lua怎么了，大多数时候不就是插件主页粘贴复制？管他用啥语言有啥差别？哪里是用啥语言的问题

键位映射，那我是不是也可以说，哎呀，不会吧，还有人www，f，t的去移动呢，咋不试试[这个插件呢](https://github.com/easymotion/vim-easymotion)，还有人放着趁手的`;`键不用非要学人家映射个`<space>`呢

为啥用neovim，因为很多你多少年知道的不知道的默认配置给你设置好了啊，不会说这样不好吧？那为啥vim也开始这样呢？？？
因为LSP这一套香啊，这不直接和ide平起平坐，不用配那么多乱七八遭还这个语言能用那个语言不行的。因为true color看着我心情好啊，因为我能多装几个自己喜欢的插件不用卡的不行啊，因为vim多少年没能有的插件，现在都only neovim了？即使vim9出了，真不是一个快慢的问题。不要说别的，就承认至少现在，neovim比vim用起来美就行了。

最下那行什么意思，可以翻译下吗？看不懂这个就像我看不懂vim里一堆CTRL_0是啥一样

**Comment by skywind3000** [comment]
说了半天就是，你不懂，你不懂，你还有理了，你这就叫反智知不知道。

还用 `;` ，你不知道 `;` 在 vim 里有重要用途的么？

只用过 MacVim 还好意思出来丢人，

Vim 没有 lsp 都出来了，ycm 早就支持 lsp 了你知道不？还有 vim-lsp, coc 都能给 vim 提供 lsp 支持，无知不是你的错，
无知可以学，犯傻气就没法救了。

再说 neovim 自动帮你设置好那一堆 defaults，vim 不这么做是因为要保持更多兼容，vim 有 tiny 模式，单片机模式，键盘有西欧键盘，阿拉伯键盘，对于西欧键盘直接按 ALT+x 就可以被 vim 识别到，但 neovim 却没法识别，必须切换输入法成国标键盘才能识别 ALT+x，vim 通过配置可以应付两种情况，你 neovim 为了简单只支持一种情况你还有理了。

用 vim/neovim 的害怕麻烦么？多写两行一次性的事情，又不是每次打开文件都要重写一遍，这种麻烦都要省，你去用傻瓜的 vscode 啊？单反相机用不来，你用傻瓜相机没人笑话你啥，你要转过来说单反不对就是你二了。

最后，有不同意见跑来人家仓库里提可以，但是请你学点礼貌，我都没跑到 neovim 的相关项目里说啥 neovim 的不对之处，你个二傻子莫名其妙跑过来一副毁天灭地的样子，动不动就是这也不行，那也垃圾，张开嘴就是秒天秒地秒空气。

你这叫犯傻知道不？

**Comment by skywind3000** [comment]
不说话没人把你当哑巴。

**Comment by Arrake-One** [comment]
我觉得大部分牛人用vim而不用nvim是没有时间折腾和懒得折腾了。。。毕竟看几百页的英文文档（包括各种插件说明文档）去配置一个工具，除非是实在太闲了。。。
