### ISSUE TITLE
mac pro 快捷键 issue

### ISSUE THREAD

**Issue by xueyouchao** [skywind3000/vim-init#9]
这两行为什么在iterm2里面失灵？我的left option 好像map在esc+， left option-> right option->也没有map其它键
noremap <silent><m-left> :call Tab_MoveLeft()<cr>
noremap <silent><m-right> :call Tab_MoveRight()<cr>

奇怪的是下面选tab是work的
noremap <silent><m-1> :tabn 1<cr>
noremap <silent><m-2> :tabn 2<cr>
noremap <silent><m-3> :tabn 3<cr>
noremap <silent><m-4> :tabn 4<cr>
noremap <silent><m-5> :tabn 5<cr>
noremap <silent><m-6> :tabn 6<cr>
noremap <silent><m-7> :tabn 7<cr>
noremap <silent><m-8> :tabn 8<cr>
noremap <silent><m-9> :tabn 9<cr>
noremap <silent><m-0> :tabn 10<cr>

**Comment by skywind3000** [comment]
你能不能整理下代码格式？

**Comment by xueyouchao** [comment]
sorry，刚发现GITHUB过滤所有<>和里面的字符，所以上面显示代码不对， 我刚装了MacVim 8.1 版本，好像左右移动tab的快捷键仍然无效，但是很奇怪选择tab的快捷键没有问题。
同样都是 option键加组合键， 如果是option加数字选tab就没有问题， option加左右键移动tab就有问题

**Comment by skywind3000** [comment]
不支持 ALT+方向键呗，换个别的试试。
